import { TextProps } from '../components/text';
import { ElementOverrideProp } from './ElementOverrideProp';
import { ButtonProps } from '../components/button';
import { CheckboxProps } from '../components/checkbox';
import { DropdownProps } from '../components/dropdown';
import { DynamicSubmitProps } from '../components/dynamicSubmit';
import { FormProps } from '../components/form';
import { InputGroupProps } from '../components/inputGroup';
import { InputHeaderProps } from '../components/inputHeader';
import { MoneyProps } from '../components/money';
import { NumberInputProps } from '../components/numberInput';
import { RadioProps, SelectProps } from '@material-ui/core';
import { RadioContainerProps } from '../components/radioContainer';
import { OpeningHoursDayProps } from '../components/openingHours/openingHoursDay';
import { OpeningHoursWeekProps } from '../components/openingHours/openingHoursWeek';
import { OpeningHoursSpecialProps } from '../components/openingHours/openingHoursSpecial';
import { SubmitProps } from '../components/submit';
import { TagsProps } from '../components/tags';
import { TextAreaProps } from '../components/textArea';
import { TimeProps } from '../components/time';
import { TimeSpanProps } from '../components/timeSpan';

export type ThemeOverrides = {
  button?: ElementOverrideProp<ButtonProps>;
  checkbox?: ElementOverrideProp<CheckboxProps>;
  dropdown?: ElementOverrideProp<DropdownProps>;
  dynamicSubmit?: ElementOverrideProp<DynamicSubmitProps>;
  form?: ElementOverrideProp<FormProps>;
  inputGroup?: ElementOverrideProp<InputGroupProps>;
  inputHeader?: ElementOverrideProp<InputHeaderProps>;
  money?: ElementOverrideProp<MoneyProps>;
  numberInput?: ElementOverrideProp<NumberInputProps>;
  radio?: ElementOverrideProp<RadioProps>;
  radioContainer?: ElementOverrideProp<RadioContainerProps>;
  openingHoursDay?: ElementOverrideProp<OpeningHoursDayProps>;
  openingHoursWeek?: ElementOverrideProp<OpeningHoursWeekProps>;
  openingHoursSpecial?: ElementOverrideProp<OpeningHoursSpecialProps>;
  select?: ElementOverrideProp<SelectProps>;
  submit?: ElementOverrideProp<SubmitProps>;
  tags?: ElementOverrideProp<TagsProps>;
  text?: ElementOverrideProp<TextProps>;
  textArea?: ElementOverrideProp<TextAreaProps>;
  time?: ElementOverrideProp<TimeProps>;
  timeSpan?: ElementOverrideProp<TimeSpanProps>;
};
